// <auto-generated />
namespace BlueBadgeProject.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RoleReconfiguredv5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleReconfiguredv5));
        
        string IMigrationMetadata.Id
        {
            get { return "202103020512073_RoleReconfiguredv5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
